import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    TreeSelect,
    Typography,
    Select,
    Divider,
    DatePicker,
    Button,
    Radio,
    InputNumber,
    Col,
    Row,
    Form,
    Input,
    Cascader,
    Switch,
    Checkbox,
    Card
} from 'antd';

import React, {useEffect} from 'react';
import {adultTix, childTix, selectDate, totalAmt} from "./index";

const {Title} = Typography;

class BoxComponent extends React.Component {
    render() {
        return (
            <Row style={{paddingBottom: '15px'}}>
                <Col xl={8}></Col>
                <Col xl={8}>
                    <Card title={`Visitor ${this.props.keyProp}`} bordered={false} style={{width: "auto"}}>
                        <Form
                            labelCol={{span: 4}}
                            wrapperCol={{span: 14}}
                            layout="horizontal"
                            style={{maxWidth: 600}}
                        >
                            <Form.Item label="Name">
                                <Input style={{fontSize: '17px'}}/>
                            </Form.Item>
                            <Form.Item label="Email">
                                <Input style={{fontSize: '17px'}}/>
                            </Form.Item>
                            <Form.Item label="Contact">
                                <Input.Group>
                                    <Form.Item
                                        name={['contact', 'code']}
                                        noStyle
                                        rules={[{required: true, message: 'Country is required'}]}
                                    >
                                        <Select bordered={false} placeholder="Country">
                                            <Select.Option value="+60">(+60)</Select.Option>
                                            <Select.Option value="+65">(+65)</Select.Option>
                                        </Select>
                                    </Form.Item>
                                    <Form.Item
                                        name={['contact', 'number']}
                                        noStyle
                                        rules={[{required: true, message: 'Number is required'}]}
                                    >
                                        <Input style={{width: '50%', fontSize: '17px'}} placeholder="Input number"/>
                                    </Form.Item>
                                </Input.Group>
                            </Form.Item>
                        </Form>
                    </Card>
                </Col>
            </Row>
        );
    }
}

export default function Booking() {
    const [hasMounted, setHasMounted] = React.useState(false);

    useEffect(() => {
        setHasMounted(true);
    }, [])
    if (!hasMounted) {
        return null;
    }
    const getForms = () => {
        let rows = [];
        for (let i = 0; i < adultTix + childTix; i++) {
            rows.push(<BoxComponent key={i + 1} keyProp={i + 1}/>);
        }
        return rows;
    }

    return (
        <>
            <Head>
                <title>Complete Booking</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Title level={2} style={{textAlign: 'left', margin: '0px', padding: '20px'}}>
                    HOME by Tales Of Paws Admission Ticket
                </Title>
                <Row>
                    <Col xl={8}></Col>
                    <Col xs={24} xl={8}>
                        <Card title="You are booking" bordered={false} style={{width: "auto"}}>
                            <Row>
                                <Col>
                                    <p>Date: </p>
                                </Col>
                                <Col xs={10} xl={16}></Col>
                                <Col>
                                    <p>{selectDate}</p>
                                </Col>
                            </Row>
                            <Row>
                                <Col>
                                    <p>Quantity: </p>
                                </Col>
                                <Col xs={8} xl={14}></Col>
                                <Col>
                                    <p>{adultTix == 0 ? '' : ` ${adultTix} x Adult`}{childTix == 0 ? '' : `, ${childTix} x Child`}</p>
                                </Col>
                            </Row>
                            <Divider/>
                            <Row>
                                <Col>
                                    <p>Total: </p>
                                </Col>
                                <Col xs={10} xl={16}></Col>
                                <Col>
                                    <p>MYR {totalAmt}.00</p>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                </Row>
                <Row>
                    <Col xl={6}></Col>
                    <Col xs={24} xl={12}>
                        <Divider orientation="left" style={{paddingTop: '10px', fontSize: '20px'}}><h2>Enter Info</h2>
                        </Divider>
                    </Col>
                </Row>
                {getForms()}
                <Row>
                    <Col xl={6}></Col>
                    <Col xs={24} xl={12}>
                        <Divider orientation="left" style={{paddingTop: '10px', fontSize: '20px'}}><h2>Disclaimer</h2>
                        </Divider>
                    </Col>
                </Row>
                <Row>
                    <Col xs={3} xl={8}></Col>
                    <Col xl={8}>
                        <Checkbox>By checking this box, I hereby acknowledge and confirm that I have read the Covid-19
                            Terms, Covid-19 Privacy Policy & Health Acknowledgement before booking my cruise.</Checkbox>
                    </Col>
                </Row>
                <Row>
                    <Col xs={3} xl={8}></Col>
                    <Col xl={8}>
                        <Checkbox>Please note that the "First Name" and "Last Name" input above should not consist of
                            any special characters (e.g. , - ? / @ ~ . etc). I acknowledge that if special characters
                            are included in the fields, the booking will be invalid and cancelled automatically upon
                            booking.</Checkbox>
                    </Col>
                </Row>
                <Row>
                    <Col xl={6}></Col>
                    <Col xs={24} xl={12}>
                        <Divider orientation="left" style={{paddingTop: '10px', fontSize: '20px'}}><h2>Discounts</h2>
                        </Divider>
                    </Col>
                </Row>
                <Row>
                    <Col xs={2} xl={8}></Col>
                    <Col xs={22} xl={12}>
                        <Input.Group compact>
                            <Input style={{width: '200px'}} defaultValue="Promo Code"/>
                            <Button type="primary">Submit</Button>
                        </Input.Group>
                    </Col>
                </Row>
                <Row>
                    <Col xl={2}></Col>
                    <Col xs={24} xl={20}>
                        <Divider/>
                    </Col>
                </Row>
                <Row style={{paddingBottom: '10px'}}>
                    <Col xl={8}></Col>
                    <Col>
                        By continuing, you acknowledge and agree to our Terms of Use.
                    </Col>
                </Row>
                <Row style={{paddingBottom: '40px'}}>
                    <Col xl={8}></Col>
                    <Col xl={8}>
                        Your booking will be submitted once you click &quot;Payment&quot;. You can choose your payment
                        method in the next step.
                    </Col>
                </Row>
                <Row>
                    <Col xl={6} md={3} xs={0}></Col>
                    <Col xl={4} md={5} xs={14}>
                        <h1 style={{
                            display: 'flex',
                            flexDirection: 'row',
                            alignItems: 'center',
                        }}>MYR {totalAmt}.00</h1>
                    </Col>
                    <Col xl={6} md={8} xs={2}></Col>
                    <Col xl={4}>
                        <Button type="primary" shape="round" size={'large'}
                                style={{background: "#fa8547"}} disabled={false}
                                htmlType="submit">
                            Payment
                        </Button>
                    </Col>
                </Row>
            </main>
        </>
    )
}
