import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    Typography,
    Select,
    Divider,
    Button,
    Col,
    Row,
    Form,
    Input,
    Layout,
    Checkbox,
    Card, Image, Progress, Space
} from 'antd';

import React, {useEffect, useState} from 'react';

import Link from "next/link";
import {citizenTix, selectDate, selectSlot, totalAmt, touristTix} from "./index";
import {bookingId} from "../components/checkout";

const {Header} = Layout;
const {Title} = Typography;
const slotMap: {
    [key: number]: string;
} = {
    0: 'Corgi - 10.30am to 12:00pm',
    1: 'Corgi - 12.30pm to 02:00pm',
    2: 'Dogs - 02.30pm to 04:00pm',
    3: 'Dogs - 05.00pm to 06.30pm',
};

export default function Payment() {
    return (
        <>
            <Head>
                <title>Complete Booking</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Row>
                    <Col xl={24}>
                        <Link href='/'>
                            <Header>
                                <Title level={2} style={{textAlign: 'center'}}>
                                    HOME by Tales Of Paws Admission Ticket
                                </Title>
                            </Header>
                        </Link>
                    </Col>
                </Row>
                <Row>
                    <Space direction="horizontal" style={{width: '100%', justifyContent: 'center',marginTop:'50px'}}>
                    <Progress type="circle" percent={100} size={"small"} />
                    </Space>
                    <Space direction="horizontal" style={{width: '100%', justifyContent: 'center',marginTop:'10px'}}><h1>You&apos;re all set!</h1></Space>
                    <Space direction="horizontal" style={{width: '100%', justifyContent: 'center',marginTop:'10px'}}>A confirmation has been sent to you.</Space>
                    <Space direction="horizontal" style={{width: '100%', justifyContent: 'center',marginTop:'10px'}}><h3>Booking Id: {bookingId}</h3></Space>
                </Row>
                <Row>
                    <Col xl={9}></Col>
                    <Col xs={24} xl={6}>
                        <Card title="Your Booking" bordered={false} style={{width: "auto", marginTop:'50px'}}>
                            <Row>
                                <Image alt={'banner'} style={{borderRadius: '10px',marginBottom:'15px'}}
                                       src="banner.jpg" preview={false}
                                />
                            </Row>
                            <Row>
                                <Col span={24}>
                                    <h4>Date: {selectDate}</h4>
                                </Col>
                            </Row>
                            <Row>
                                <Col span={24}>
                                    <h4>Slot: {slotMap[selectSlot]}</h4>
                                </Col>
                            </Row>
                            <Row>
                                <Col span={24}>
                                    <h4>Quantity: {citizenTix == 0 ? '' : ` ${citizenTix} x Citizen `}{citizenTix==0 || touristTix == 0?'':','}{touristTix == 0 ? '' : ` ${touristTix} x Tourist`}</h4>
                                </Col>
                            </Row>
                            <Divider/>
                            <Row>
                                <Col span={14}>
                                    <h3>Total: </h3>
                                </Col>
                                <Col span={10}>
                                    <h3>MYR {totalAmt}.00</h3>
                                </Col>
                            </Row>
                        </Card>
                    </Col>
                    <Col xl={9}></Col>
                </Row>
               <Row>
                   <Col>
                   </Col>
               </Row>
            </main>
        </>
    )
}
