import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
    Typography,
    Col,
    Row,
    Layout
} from 'antd';

import React, {useEffect, useState} from 'react';

import Link from "next/link";
import {
    Elements
} from "@stripe/react-stripe-js";
import {loadStripe} from "@stripe/stripe-js";
import CheckoutForm from "../components/checkout";
import {Appearance, StripeElementsOptions} from "@stripe/stripe-js/types/stripe-js/elements-group";
import envVar from '../env_var';
import {citizenTix, referralId, selectDate, selectSlot, totalAmt, touristTix} from "./index";
import {useRouter} from "next/router";
import {contactFormValues} from "./form";

const {Header} = Layout;
const {Title} = Typography;

export let bookingId;

export default function Payment() {
    const [clientSecret, setClientSecret] = useState("");
    const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);
    const router = useRouter();

    const trackPayment = () =>{
        const myHeaders = new Headers();
        myHeaders.append("Content-Type", "application/json");

        const raw = JSON.stringify({
            "referral_id": referralId,
            "booking_day": selectDate,
            "booking_slot": parseInt(String(selectSlot), 10),
            "citizen_ticket_count": citizenTix,
            "tourist_ticket_count": touristTix,
            "customer_info": contactFormValues
        });

        fetch(`${envVar.Env}/api/v1/welcome/payment`, {
            method: 'POST',
            headers: myHeaders,
            body: raw,
            redirect: 'follow'
        })
            .then(response => response.json())
            .then(result => {
                console.log(result)
                bookingId = result.booking_id;
            })
            .catch(error => {
                console.log('error', error)
            });
    }

    useEffect(() => {
        if (totalAmt == 0) {
            router.push(`/`)
        }
        // Create PaymentIntent as soon as the page loads
        fetch(`${envVar.Env}/api/v1/payment/create-payment-intent`, {
            method: "POST",
            headers: {"Content-Type": "application/json"},
            body: JSON.stringify({tickets: {citizen_ticket_count: citizenTix, tourist_ticket_count: touristTix}}),
        })
            .then((res) => res.json())
            .then((data) => {
                console.log(data)
                if (data.response_meta.error_code == 0){
                    trackPayment();
                }
                setClientSecret(data.client_secret)
            });
    }, []);

    const appearance: Appearance = {
        theme: 'stripe',
    };
    const options: StripeElementsOptions = {
        clientSecret,
        appearance,
    };

    // useEffect(() => {
    //     setHasMounted(true);
    // }, [])
    // if (!hasMounted) {
    //     return null;
    // }

    return (
        <>
            <Head>
                <title>Complete Payment</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Row>
                    <Col xl={24}>
                        <Link href='/'>
                            <Header>
                                <Title level={2} style={{textAlign: 'center'}}>
                                    HOME by Tales Of Paws Admission Ticket
                                </Title>
                            </Header>
                        </Link>
                    </Col>
                </Row>
                {/*<Row>*/}
                {/*    <Col xs={24} xl={24}>*/}
                {/*        <Image alt={'banner'} style={{borderRadius: '25px',marginLeft:'auto',marginRight:'auto',width:'80%',display:'block',paddingBottom:'50px'}}*/}
                {/*               src="banner.jpg" preview={false}*/}
                {/*        />*/}
                {/*    </Col>*/}
                {/*</Row>*/}
                <div className="stripe-body">
                    {clientSecret && (
                        <Elements options={options} stripe={stripePromise}>
                            <CheckoutForm/>
                        </Elements>
                    )}
                </div>
            </main>
        </>
    )
}
